name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Release to Github and NPM
        uses: cycjimmy/semantic-release-action@v4.1.0
        with:
          branches: |
            [
              'main'
            ]

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        timeout-minutes: 10
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
